test : test.o trajet.o TrajetSimple.o 
	g++ -o test test.o trajet.o TrajetSimple.o

test.o : test.cpp
	g++ -c test.cpp

TrajetSimple.o : TrajetSimple.cpp
	g++ -c TrajetSimple.cpp

trajet.o : trajet.cpp
	g++ -c trajet.cpp
