testtri : testtri.o trajet.o liste_chainee.o TrajetSimple.o TrajetCompose.o Catalogue.o
	g++ -o testtri testtri.o trajet.o liste_chainee.o TrajetSimple.o TrajetCompose.o Catalogue.o

testtri.o : testtri.cpp trajet.h TrajetSimple.h
	g++ -c testtri.cpp

trajet.o : trajet.cpp trajet.h
	g++ -c trajet.cpp

liste_chainee.o : liste_chainee.cpp liste_chainee.h
	g++ -c liste_chainee.cpp

TrajetSimple.o : TrajetSimple.cpp TrajetSimple.h trajet.h
	g++ -c TrajetSimple.cpp

TrajetCompose.o : TrajetCompose.cpp TrajetCompose.h trajet.h
	g++ -c TrajetCompose.cpp

Catalogue.o : Catalogue.cpp Catalogue.h
	g++ -c Catalogue.cpp

